---
version: 2.1
parameters:
  organization:
    type: string
    default: ""
  repository:
    type: string
    default: ""
  branch:
    type: string
    default: "master"

jobs:
  register-vm-image:
    docker:
      - image: circleci/python:stretch
    steps:
      - checkout
      - run:
          name: Register VM Image to VM image repository
          command: |
            curl -u ${CIRCLECI_TOKEN}: \
             -X POST --header "Content-Type: application/json" \
             -d '{ "branch": "<< pipeline.parameters.branch >>" }' \
             https://circleci.com/api/v2/project/gh/<< pipeline.parameters.organization >>/<< pipeline.parameters.repository >>/pipeline

workflows:
  version: 2
  build:
    jobs:
      - register-vm-image:
          context:
            - CIRCLECI 
